{{- if .Values.enabled }}
{{- $name := include "trace.name" . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-api
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: trace-api
  policyTypes: [Ingress]
  ingress:
    - ports: [{protocol: TCP, port: 8443}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}-node
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: trace-node
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name | quote }}
              app.kubernetes.io/component: trace-api
      ports: [{protocol: TCP, port: 9443}]
  egress: []
{{- end }}
