{{- if .Values.nodeContext.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-memlens-node-context
  namespace: {{ .Values.namespace.name | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kube-memlens-node-context
  policyTypes: [Ingress, Egress]
  ingress: []
  egress:
    - to:
{{- range .Values.nodeContext.apiServerCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
{{- end }}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    - to:
{{- range .Values.nodeContext.nodeCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
{{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.nodeContext.kubeletPort }}
{{- end }}
