apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-memlens-agent
  namespace: {{ .Values.namespace.name | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-memlens-collector
  namespace: {{ .Values.namespace.name | quote }}
automountServiceAccountToken: false
