{{- if .Values.collector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kube-memlens-collector
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: kube-memlens-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kube-memlens-collector
  ports:
    - name: https-extension
      port: 443
      targetPort: extension
{{- end }}
