#!/usr/bin/env python3
"""Render a private provider proposal without contacting Kubernetes or a provider."""

import argparse
import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path

from common import ContractError, digest, load, require, utc_text, write_new
from observer_specs import ephemeral_observer, host_observer, host_policy
from provider_plan import serving_ca, validate_config, values
from provider_source import bind_files
from workload import deployment

HACK = Path(__file__).resolve().parents[1]
REPOSITORY = HACK.parent
sys.path.insert(0, str(HACK))
from verify_chart_archive import ArchiveError, verify_archive, verify_chart_metadata  # noqa: E402


def local_command(args, repository=REPOSITORY):
    environment = dict(os.environ, KUBECONFIG=os.devnull, GIT_TERMINAL_PROMPT="0", GIT_NO_LAZY_FETCH="1")
    try:
        result = subprocess.run(args, cwd=repository, env=environment, capture_output=True,
                                timeout=60, check=True)
    except (OSError, subprocess.SubprocessError) as error:
        raise ContractError("offline Git or Helm validation failed") from error
    require(len(result.stdout) <= 2 * 1024 * 1024, "offline command output exceeded its bound")
    return result.stdout


def private_text(path, text):
    # Files are exclusively created inside the new mode-0700 proposal directory.
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as target:
        target.write(text)
    return "sha256:" + hashlib.sha256(text).hexdigest()


def review_preview(raw):
    text = raw.decode("utf-8")
    text, count = re.subn(r'(?m)^(  (?:ca\.crt|tls\.crt|tls\.key|caBundle):) .+$',
                          r'\1 "<generated by Helm at installation>"', text)
    require(count == 4, "generated TLS preview layout differs from the reviewed chart contract")
    return ("# REVIEW ONLY: generated TLS material is omitted; do not apply this preview.\n" + text).encode()


def prepare(profile, config, output, repository=REPOSITORY):
    c = validate_config(profile, config)
    output = Path(output)
    require(output.is_absolute() and not output.exists(), "proposal directory must be new and absolute")
    chart = repository / "charts/kube-memlens"
    bind_files(repository, c["sourceCommit"], "charts/kube-memlens", local_command)
    verify_archive(c["chartArchive"], chart)
    verify_chart_metadata(c["chartArchive"], chart)
    tool_commit = local_command(["git", "rev-parse", "HEAD"], repository).decode().strip()
    profile_path = "hack/node-qualification/profiles/" + profile["id"] + ".json"
    require(profile == load(repository / profile_path), "proposal must use a canonical checked-in profile")
    bind_files(repository, tool_commit, profile_path, local_command)
    bind_files(repository, tool_commit, "hack/provider-profiles/" + c["inventoryProfile"] + ".json", local_command)
    dirty = bool(local_command(["git", "status", "--porcelain", "--untracked-files=all"], repository).strip())
    provider_values = repository / "hack/provider-values" / (c["inventoryProfile"] + ".yaml")
    require(provider_values.is_file(), "canonical provider values are missing")
    bind_files(repository, c["sourceCommit"], provider_values.relative_to(repository).as_posix(), local_command)
    output.mkdir(mode=0o700)
    # A failed render leaves a private incomplete bundle, never a prepared plan.
    # Do not remove it recursively: an operator may have added another file.
    outputs = {}
    for phase in ("baseline", "enabled"):
        overrides = values(profile, c, phase == "enabled")
        path = output / (phase + "-values.json")
        write_new(path, overrides)
        raw = local_command(["helm", "template", "kube-memlens-node-qualification", c["chartArchive"],
                             "--namespace", c["namespace"], "--kube-version", c["kubernetesVersion"],
                             "--dry-run=client", "--values", str(provider_values), "--values", str(path)], repository)
        outputs[phase + "PreviewDigest"] = private_text(output / (phase + ".preview.yaml"), review_preview(raw))
    ca = serving_ca(c["kubeletCAFile"])
    trust = {"apiVersion": "v1", "kind": "ConfigMap",
             "metadata": {"name": "node-context-trust", "namespace": c["namespace"]},
             "data": {"ca.crt": ca.decode("ascii")}}
    write_new(output / "serving-trust.json", trust)
    write_new(output / "workload.json", deployment(profile["workload"], c["namespace"],
                                                  {"nodeSelector": values(profile, c, True)["agent"]["nodeSelector"]}))
    observer_image = profile["workload"]["image"]
    selector = values(profile, c, True)["agent"]["nodeSelector"]
    write_new(output / "host-observers.json", {"apiVersion": "v1", "kind": "List", "items": [
        host_policy(c["namespace"]), host_observer(c["namespace"], observer_image, selector)]})
    write_new(output / "ephemeral-observers.json", {
        component: ephemeral_observer(observer_image, component) for component in ("agent", "node-context")})
    write_new(output / "configuration.private.json", c)
    names = ("baseline-values.json", "enabled-values.json", "baseline.preview.yaml", "enabled.preview.yaml",
             "serving-trust.json", "workload.json", "host-observers.json", "ephemeral-observers.json",
             "configuration.private.json")
    files = {name: "sha256:" + hashlib.sha256((output / name).read_bytes()).hexdigest() for name in names}
    plan = {
        "schemaVersion": 2, "state": "prepared-not-approved", "qualified": False,
        "providerRunStarted": False, "preparedAt": utc_text(),
        "profile": {"id": profile["id"], "digest": profile["profileDigest"]},
        "configurationDigest": digest(c, "configurationDigest"),
        "qualificationToolCommit": tool_commit, "toolSourceDirty": dirty,
        "servingTrustDigest": "sha256:" + hashlib.sha256(ca).hexdigest(),
        "rendered": outputs, "files": files,
        "measurement": dict(profile["measurement"]), "budgets": dict(profile["budgets"]),
        "observation": {"method": "kubernetes-probes-v1", "image": observer_image},
        "verificationStillRequired": [
            "Explicit owner approval of this target, immutable artefacts and rendered resources",
            "Fresh provider inventory and live binding to the selected context and exact two-Node pool",
            "Standard deep-mode prerequisites, including aggregation-proxy identity and schedulable Linux Nodes",
            "Candidate image/source and executable identity verification; local hashes alone do not prove image provenance",
            "Serving certificate chain, address, expiry and audience checks on each selected Node",
            "Direct nodes/stats permission and denial controls without nodes/proxy",
            "NetworkPolicy enforcement and reviewed read-only host observation access",
            "Fixed workload, baseline/enabled measurements, natural rotation and lifecycle recovery",
            "Separately approved provider Node replacement, sanitised evidence and independent review",
        ],
        "cleanupRequirements": [
            "Refuse existing namespaces, releases and conflicting chart-owned cluster resources before installation",
            "Record created namespace and resource UIDs; delete only matching resources owned by this run",
            "Uninstall the recorded release, remove owned trust/workloads/RBAC and verify their absence",
            "Obtain provider-owned confirmation that disposable provider resources have been removed",
        ],
    }
    plan["planDigest"] = digest(plan, "planDigest")
    write_new(output / "plan.private.json", plan)
    return plan


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("profile", "configuration", "output"):
        parser.add_argument("--" + name, required=True)
    args = parser.parse_args()
    try:
        configuration = Path(args.configuration)
        require(configuration.stat().st_mode & 0o077 == 0, "private configuration must not be group/world readable")
        prepare(load(args.profile), load(configuration), args.output)
        print("Private provider proposal prepared; no provider action or approval performed.")
        return 0
    except (ContractError, ArchiveError) as error:
        print(f"Provider preparation failed: {error}", file=sys.stderr)
        return 2
    except (OSError, ValueError, TypeError, KeyError):
        print("Provider preparation failed; check file access and configuration field types.", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
